# Introduction {#intro}
Francois Nguyen: Personal Profile

I was born in Hue, Vietnam in the late 1950’s. Attending French schools with an interest in the sciences, I was always a good student and often voted class president by my peers. My family moved to Saigon where I attended high school at Ngo Quyen and passed the highly competitive baccalaureate exam. In 1975, I left Saigon on my brother’s helicopter leaving half my family including my parents behind. Not knowing I would not return for 20 years, I came to the United States seeking refugee resettlement.

I arrived in Minnesota, took English classes at Macalester College, then was accepted as a Freshman at St. Thomas College the same year. Learning English very quickly, I did well in my courses and made many friends. I was President of the International Student Organization for two years, involved with the Minnesota Council of Private Colleges to bring more minorities in to private colleges, and worked on the Economic Security Department’s Governor’s Special Task Force on Minority Employment.

After college I worked for three summers as a chemist intern for the St. Paul Water Department. I worked part time in the Bilingual department at St. Paul Technical and Vocational Institute. I received my Masters in Education from La Verne University in 1982.

I was awarded a full time contract as a Bilingual Instructor at St. Paul Technical and Vocational Institute in 1982 and received tenure in 1985. I continue to teach Math, Computers, and English as a Second Language at St. Paul Technical College which is part of the Minnesota State Colleges and University system.

Since 1975, I have always been very active in the Vietnamese Community. I have provided initial assistance to Vietnamese newcomers. I have represented the Vietnamese community as a spokesperson on issues related to refugee resettlement. I continue to mentor Vietnamese in cross cultural issues.

I hosted a radio talk show on news and information about the Vietnamese community.
I participated as a panelist in the WCCO town meeting for the 10 year anniversary of the Vietnam fall to communism. I participated on committees for the Chamber of Commerce to promote refugee employment.

I was hired as a Coordinator for the St. Paul Foundation’s Supporting Diversity in Schools project which was set up to combat racism in the St. Paul Public Schools.

I was selected as a participant in the Great Lakes Governor’s Council Pioneering Partnership which focused on technology innovations in schools.

I coordinated and instructed St. Paul Urban League’s Summer Science Institute which provided career exploration for St. Paul high school students. I also coordinated and instructed the St. Paul Connections program for afterschool career exploration for St. Paul high school students.
