# Impact Statement

Francois Nguyen is a seasoned teacher. His experience and passionate dedication to teaching has made him an outstanding role model for his students and colleagues. Through four decades of teaching math and statistics, Francois has been a pioneer leader implementing technology in the classroom at an early stage back in the early 90s. Francois was selected to participate in various capacities to help the college with equity and inclusion. In 2017, Francois was selected to be a member to develop the racial and inclusion diversity plan. This plan was implemented and made Saint Paul College a trauma-informed and anti-racist institution. His enthusiasm in teaching and strong desire to help has inspired many students to strive for success. As a former refugee himself, he understands immigrant students and helps them overcome barriers. He advocates for changing the minds and attitudes towards the immigrant community. He has earned respect and recognition from his community. Francois has impacted so many lives throughout the years.
