# Teaching Philopsophy

Francois Nguyen’s Philosophy of Teaching
Connection, Commitment, and Community
Connection so students feel comfortable,
Commitment to learning the content,
Community supporting one another.

Each student comes to my class with their unique background, experiences, abilities, and intelligence. My responsibility is to discover these attributes and create conditions so they can develop to their fullest potential. If a student cannot learn the way I teach, then I must teach the way they learn. There is no teaching method that applies to everyone. I must constantly change the way I do things depending on the situation I am in. I meet students where they are.

Some of my students did not have formal education. Some of my students are the first in their family to go to college. Some came from backgrounds where English was a barrier for them to learn math. I must create a nurturing environment so they feel comfortable and can feel more confident to learn and discover for themselves. In this way they can overcome obstacles. Most students who come to my class have math anxiety. My job is to get to know them, tell some jokes, tell stories about my own life or have them tell stories about themselves. This will create a comfortable community where students respect one another and will feel safe to learn. “I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.” -Maya Angelou

Responsibility for their own learning is also very important. I believe that hard work will produce good results. I want my students to practice and work together to instill deep learning in their minds so they can learn better for themselves. Students have to be actively engaged in the learning process. William Butler Yeats said “Education is not the filling of a pail, but the lighting of a fire.” Students should feel excited about what they are learning so they can feel a sense of inspiration and enjoyment. I want to make sure my class is a joyful learning experience applying theories to practice and dealing with real world situations. Students are also curious to experience different realities than what they are used to. 

In one class who were mostly native speaking English students in the technical areas of welding, carpentry, and machine tool operators, I had to create lessons that were practical and tailored to their own trade areas so they can feel connected to their own trades. I also have a lot of immigrant students who know math well, but have difficulty with English. In this case I pair these students up with native English speakers so they can help each other. This works especially well with word problems which are difficult for everyone. Working together and getting to know one another develops respect for one another. I believe in cooperative learning, where they do group work and projects rather than filling their time with lots of assignments just to keep them busy. 

Math should be about self-discovery to finding solutions. Math is not just about numbers and formulas; it requires students to do a lot of active reasoning and critical thinking. There are multiple approaches to solving problems. Students need to try all options and figure out which ones are best suited to them. Sometimes they try and fail but, in my class, failure is an option. When student fail, they learn from their mistake and strive for the best result and help them build the resiliency and bring them success next time. Learning is lifelong experience. Nelson Mandela said, “Education is the most powerful weapon which you can use to change the world.” My students need mathematics so they can go out and do what is necessary for their careers. Through inquiry, students can explore different environments in science and math. 

Sometimes we must give up our control and have the students feel free to communicate and come up with a solution their own way. Sometimes we have to be the guide on the side and not the sage on the stage. When students bring in their own ideas, other students will see that there are multiple ways of solving problems. Diversity of ideas and opinions is highly valued in my classes.

In conclusion, I sometimes hear students tell me their parents enjoyed being in my class and now they are in my class, that is the most rewarding feeling of satisfaction to serve multiple generation. I feel like I am making an important impact on their lives.

Thank you very much.


