# Vision:
Vision:
To work with immigrant/minority populations in urban public schools to improve their quality and opportunities of education, and to influence policy that would achieve that goal. To examine the role of education in Asian culture and to document the education public system. To examine the urban issues of poverty and education and look for ways to improve inner-city kids lives through self agency and through policy. 


Academic: Strong problem-solving, critical judgment, conceptualization, realization, organization and research skills; curious and enthusiastic; comfortable in unstructured or loosely structured academic environments where initiative, creativity and individual exploration and action are encouraged. 


In in Asia they have saying that chaos is automatic form of order so sometime you don't see everything structure and you cannot control the classroom and tell stone what to do all the time you allow them to have time and space to show that they can take Josh on of their own learning I wouldn't soon too be responsible and understand how they can connect to the world and use their own critical thinking skills to solve the problem that they might encounter
I believe my role as a teacher nor is no longer it's a lecturer are the person in front of the classroom lecture and tell provide information to students I think my role become more like a first facilitator I have two take charge and step aside and less student work together and evaluate together they process all those I have a planned fixed plan two guys stood on what need to be done
In my class I have a multiple method of teaching rather than give them a lot assignments I give them few but they assignment like group project so they can work together and see how they can connect to the real world metamatics is not just a number but it's a abstract sometimes abstract concept stone sometimes they see wrong or right but there are many different ways to solve the same problem and I want to have student used that kind of thinking to work on their own
Mortal stone come to my class with math anxieties because they have not learn math for a long time so I want to make it more exciting and fun experience for them so they can feel confident and not afraid of failing I believe sometimes you have to fail in order to learn so failing is an option and through repetition and hard work and persistence student whoa fiber solution
I want to create the classroom that is nurturing and understanding some of our students who are and urban sandling and they come to the class with different background and some of them are for generation of Carlos so they never had experience navigating around the campus fighting the resources so as the teacher I am the frontline worker I deal with them every day so anything debt can be benefit to them we want to make as a community of learners and connect to one another and to help one another to learn I learn a lot of things from my student more some of my students are very well versed in technology so they bring in some perspective off day cultural background and skills that make the classroom is open to all perspectives.

 
Phylosophy:
I have been teaching in education for almost 40 years my philosophy it keep changing to be a better teacher a bagger college on a better friend fall and a barrier for the community that I work for
But I have a strong strong foundation in belief in my principal and philosophy of teaching new life my basic philosophy is based on the belief that student mine it's not an empty bottle that needs to fill with water empty bar on it to fill with with education each student come to my class brought in bring in with different skills ability different background and different ways of learning my job is try to discover what are the condition that had them to improve and exciting to learn each student cannot learn the weight I teach but adjust the way they learn
I believe failure is an option failure and mistake is valuable lesson it's not measure by immediate result but rather they selling the Long live learning education is not but people are method that apply to everyone for every situation student should rare you the way they learn and shell discover by observe discover end the lies and evaluate I believe in student Practice teacher practice and together teacher and student practice and five ways to discover and finally student can take the learning and and come up with they own way of learning I believe the student learned best when they have a nurture environment friendly respectful and four of Joyce and happy they ability to learn is sky limit and we provide necessary 2 so they can learn Monahan one said help us fulfill basic needs first and innovation will follow William Butler Yeats one said education is not like to fill up the empty tank with water but rather light a light this saying it also my teaching philosophy I believe the signs of learning from mathematics for them is the experience that they feel more meaningful as the person lived in the community for a long time I have inherited all the benefit from the generation and the community I live in so education is raised strong weapon to help people change life I have impacted a lot of immigrant population which including the community of colors, the 4th generation college and the people who have disrupted in their formal education My philosophy is based around this idea that we have students a student can have them cell that is the great motivation for students to study hard so they can be a productive citizen to help the community Nelson Mandela once said education is the strongest weapon that you can changed the war this is the greatest philosophy that I believe in the generation that they study now will be the leaders for tomorrow
I live long enough to see the benefit of vocational training and liberal art irrigation my student one of my one of my students carida with pregnant in my class and 20 years later I have student coming and said that my mother used to be in your class when I was in her warm so I learned twice in your class that is the greatest feeling that I give an impact on student life
I have dealt a lot of student who are fearful of meth but they need mathematics communication to complement their heart skills in trade the war now is required of collaboration so by working together student word school from one another each person bring in different perspective and creativities and together they discover the confidence and a nurturing environment that can benefit from one another in my class I have different student from different backgrounds white working class trace student and immigrant student indifferent country and backgrounds so when they together I want create a friendly respectful classroom environment so everybody enjoy one another and respect one another to learn it takes time effort patient and understanding. With technology student Ken contribute and feel comfortable to give their opinion and input so that everyone is a part of learning community we respect value one another best the community I want to create so we can live peacefully and enjoy our benefit from one another so when a stone leave my classroom they feel they will contribute and have back to their community. Safe. 

Student feedback:

Intermediate Statistics was a great class. Coming in, I was expecting a traditional math course that would follow the lecture, homework, and exam format. Instead, I was presented with an engaging project-based class that allowed me to explore my interests while learning more about the application of statistics. I really enjoyed the open discussion format of the lectures.  Professor Francois made sure to incorporate current events to explain more theoretical topics. We discussed the 2020 election, COVID-19, and other data-driven topics.  As a data science major, I appreciated the class projects which required us to find reliable data sources and prepare them for analysis. If you are interested in research, open discussion, and being creative with statistics, I highly recommend this class.





## math example

$p$ is unknown but expected to be around 1/3. Standard error will be approximated

$$
SE = \sqrt{\frac{p(1-p)}{n}} \approx \sqrt{\frac{1/3 (1 - 1/3)} {300}} = 0.027
$$

You can also use math in footnotes like this^[where we mention $p = \frac{a}{b}$].

We will approximate standard error to 0.027[^longnote]

[^longnote]: $p$ is unknown but expected to be around 1/3. Standard error will be approximated

    $$
    SE = \sqrt{\frac{p(1-p)}{n}} \approx \sqrt{\frac{1/3 (1 - 1/3)} {300}} = 0.027
    $$
