# Culture

Culturally Responsive Teaching and Pedagogy 

At Saint Paul College, students come from a wide variety of different cultures speaking many different languages and having various educational backgrounds. As a former refugee himself, Francois Nguyen is very conscious about cultural biases and practices in education. Francois works diligently to minimize and combat cultural biases in the classroom and in higher education in general. 

Many math books and curricula use outdated biases frequently in their lessons. One example is the frequent use of sports analogies which many immigrants do not automatically understand not being natives of American sport culture. There are usually only Anglo names and often there are gender stereotypes. It is important for Francois to point this out and let students reframe problems so students can focus on the math and not be confused by the culture. 

 

Time is another important cultural difference he pays attention to. Students who are not native born Americans, usually have problems with due dates and other time tables, so Francois makes a point of clearly communicating expectations with frequent reminders so students complete assignments on time. 

 

Money is a factor for all students and Francois uses Direct Digital to incorporate E-Textbooks and the My Math Lab portal to give students electronic access to materials. 

 

A strong believer in constructivist learning, Francois always incorporates group discussions in his classes so students can share their own experiences and feel actively engaged. Math required lots of practice and memorization. This approach gets students more involved in something thought provoking and creative. 

 

Francois has collaborated with other departments within the campus to facilitate special activities and career development. He has worked to promote STEM competitions through a Math Club where one of his students received second place in a national competition. He has also collaborated with outside institutions. He is proud of a Nano Technology project he worked on with some math and chemistry students at the University of Minnesota. This was an opportunity to see nano technology applied in Waver and Microchip research and development. Francois collaborated with the Roseville School District to help develop math syllabi in trade areas so students can prepare for entering college in a trade program. 

 

Francois has gone above and beyond teaching math during the summer which may be more convenient for students with non traditional schedules. He taught in the Summer Bridge program helping high school students in the Metro area take math while they explored training programs offered at Saint Paul College. He has worked tirelessly to make education more accessible for minorities and non-traditional students of all kinds. 

 

 

 

 
