# Services

Service to Students, Profession, Institution, System to Advance Teaching Excellence

Throughout his forty years of teaching at Saint Paul College, Francois Nguyen has participated in numerous leadership roles and sat on countless committees. These have all been to improve services to students, make improvements to the campus, and advance the system for teaching excellence.

Currently Francois is a member of the Diversity and Inclusion Committee. This committee’s mission is to promote diversity at the college. Under the leadership of Wendy Robinson, Francois is part of the faculty and staff of color. They meet and discuss solutions to various problems brought on by the pandemic and other ongoing systemic problems. As was seen in the aftermath of the George Floyd tragedy, it is important now more than ever before to recruit and retain faculty of color reflecting the diversity of the college's student population. Since Francois has been teaching at the college for 40 years, he represents the ultimate role model for what it takes to remain in an inner city institution.

Fracois has worked with various communities of color to bring cultural awareness, closing the gap and promoting understanding of the commonalities among different groups. Even though he is not a Muslim himslef, he served as the advisor for the Muslim Student Association for many years. He encouraged these students to bring in guest speakers and initiate other activities which help these students take leadership roles to serve their fellow students in understanding Islamic cultural values bridging the gap to finding common values for all.

Always willing to help promote student success, Francois has participated in workshops to promote STEM programs, mentored international students navigating academic support systems, and participated and supported the ARTI (Anti-Racist Trauma Informed) group for students and staff members struggling with issues. 

In 2008, Francois was selected to represent MSCF faculty for the Minnesota Online Council to advise MinSCU about online learning throughout the system. All these things and more have been an integral part of Francois daily life at Saint Paul College.

 
