# Content 

Expertise and Professional Growth:

Francois Nguyen has an impressive forty years of teaching experience. A native of Vietnam, he grew up speaking both Vietnamese and French and after moving to the US learned both English and Spanish. He loved education as a young child, did extremely well academically growing up during the Vietnam war, escaped to the US and continued his education entering college after learning English for only a few months. He was hired as a teacher at Saint Paul College after finishing his Master’s Degree and has been there ever since. He brags that he has not spent even one year of his life out of school! Francois is passionate about teaching and helping students achieve education for employment. He is a positive thinker and believes that learning is a lifelong skill.

Francois consistently attended workshops and seminars to update his skills in teaching pedagogy and the latest technology. He attended workshops in how the brain learns to make his teaching more effective and produce better results in student learning. He attended a workshop in the summer of 2021 with 40 math and construction teachers to learn how to apply math in the trade area of Geometry in Construction, and Algebra in Manufacturing  Processing, Entrepreneurship and Design (AMPED). This professional development opportunity allowed the St. Paul Consortium of instructors to build relationships across the secondary and postsecondary pipeline as well as across departments including trades, math, and business. It also provided instructors the opportunity to learn about teaching best practices and ways to model similar course work for students that transition from high school to Saint Paul College. 
Francois recently attended classes in Data Science to learn how to apply R language to teach statistics. This enables students to learn statistics through models and practical research projects.
Francois strives for fair treatment of all students by communicating appropriate expectations, meeting them where they are, and helping them achieve their full potential. His continued curiosity in new educational practices as well as his interest in helping students learn has served him very well in keeping students interested and motivated to continue their learning journey.




