
# Assessment
Standards for Assessments of Student Learning and Performance

Francois Nguyen has always had high expectations for student learning. He establishes the highest standard for students to follow, communicates directly and clearly with students, yet he allows for flexibility and works with students where they are.

His math class learning outcomes match and align with college learning outcomes. Regularly working with the curriculum and assessment coordinator, he collects data and measures student learning outcomes to make sure they match student success rates which are valid and consistent. Francois participates regularly in the program advisory board to seek input for what the latest math skills are that will relate to the college’s trade areas as well.

For formative assessments, all items of homework and quizzes are listed and clearly communicated with students. Students can have many tries to complete homework because it gives them more practice each time. They may take quizzes many times as well and are given time to review often so they will feel ready and have less anxiety about the exams. In some cases Francois allows students to work on projects and present them to the class for peer review which is always a fun interactive learning activity.

For summative assessments, midterms, finals, and projects are provided to assess student learning outcomes. Evaluating the assessments of all courses and rotating the content through the years guarantees reliability and consistency.

Finally Francois encourages students to reflect on their own learning to find ways to improve. Learning by reflection allows students to assess themselves honestly and find innovative ways to improve their learning. Failure is an option so students continue to learn from their mistakes and increase their resilience.

